### ISSUE TITLE
How to use this in ejabberd 17.04 

### ISSUE THREAD

**Issue by Hassnain-Raza-Alvi** [derWhity/node-ejabberd-auth#3]
Hi,
I want to know how to use this in ejabberd 17.04.
I wrote it as instructed and added following lines in ejabberd.yml 

```
auth_method: external
extauth_program: "node ~/ejabberd-auth/index.js"
```

But it does not seem to work. In ejabberd logs i see error from external script and it says 
**No Response.**

Can you give me an example to use this in ejabberd?

**Comment by Hassnain-Raza-Alvi** [comment]
Also ejabber logs show the following lines 
```
2017-04-25 10:28:26.064 [critical] <0.25618.0>@extauth:loop:141 extauth script has exitted abruptly with reason 'normal'
2017-04-25 10:28:26.276 [critical] <0.25619.0>@extauth:loop:141 extauth script has exitted abruptly with reason 'normal'
```
Can anyone tell what's the issue?

**Comment by derWhity** [comment]
Hi,

it seems that you tried to execute the library itself instead of using it in your own project.

`ejabberd-auth` is not meant to be used directly. Instead, you have to provide your own authentication methods and run ejabberd-auth with it. Like stated in the readme, use

```js
require('ejabberd-auth').run({
    actions: {
        auth: function(done, userName, domain, password) {
            // Some auth to be done here
            done(true); // or done(false) if the authentification has failed
        }
    }
});
```
from your code to run ejabberd-auth providing your own functions for `auth`, `isuser` and `setpass`.
